source 'https://rubygems.org'

gem 'rails', '4.0.13'                                  # Web applitation framework
gem 'mysql2'                                          # MYSQL Database Adapter
gem 'tiny_tds'                                        # A modern, simple and fast FreeTDS library for Ruby using DB-Library
gem 'activerecord-sqlserver-adapter', '~> 4.0'        # MSSQL server database connector

gem 'jquery-rails',                                   # JQuery asset handling
gem 'jquery-ui-rails'
gem "protected_attributes"
gem 'valvat'                                          # European Vat Number Validation

gem 'hobo', :git => 'https://github.com/Hobo/hobo.git'  # web application meta framework from Github
gem "hobo_will_paginate"                              # pagination support
gem "hobo_bootstrap", path:"vendor/gems/hobo_bootstrap"
gem "hobo_clean_admin", "2.1.1"

gem 'bootswatch-rails'                                # Bootstrap Bootswatch themes
gem "hobo_jquery_ui", "2.1.1"                         # JQuery UI asser handling

gem "hobo_bootstrap_ui", path:"vendor/gems/hobo_bootstrap_ui"
gem "hobo_w2ui", path:"vendor/gems/hobo_w2ui"         # w2ui integration
gem 'yajl-ruby', require: 'yajl'                      # faster  json parser

gem "bootstrap-slider-rails"

gem "jquery-ui-themes", "~> 0.0.4"                    # JQury Ui theming

gem "paperclip"                                       # attachment handling
gem 'hobo_paperclip', :git => "https://github.com/Hobo/hobo_paperclip.git", :branch => "master"
                                                      # Paperclip Hobo integration
gem "ckeditor", :git => "https://github.com/galetahub/ckeditor.git"
                                                      # WYSIWYG Editor
gem "hobo_ckeditor"                                   # CKEditor integration
gem "paper_trail", '~> 3.0.0'                         # historization on object level
gem "ancestry"                                        # hierarchical data structures
gem "acts_as_list"                                    # list structures
gem 'acts-as-taggable-on', '~> 3.4'                   # tagging

gem "messengerjs-rails"                               # Messenger Javascript Framework assets
gem 'traco'                                           # model attribute translations
gem 'jbuilder', '~> 1.2'                              # a simple DSL for declaring JSON structures

gem 'roo'                                             # more sophisticated Excel spreadsheet generation
gem 'sass-rails', '~> 5.0.3'                          # Sass support
gem "less-rails"                                      # Less support
gem 'coffee-rails', '~> 4.0.0'                        # Coffeescript support
gem 'therubyracer', :platforms => :ruby               # Javascript engine
gem 'uglifier', '>= 1.3.0'                            # Code minimizer

gem "font-awesome-rails"                              # Font awesome icon font
gem "squeel"                                          # active record improvements
gem 'whenever', :require => false                     # cronjob management
gem 'private_pub'                                     # Private Pub Sub System using Faye
gem 'wicked_pdf'                                      # Pdf Generation
# Sourceforge Package is more recent, see github docs for installation:
# gem 'wkhtmltopdf-binary'                            # Pdf Generation

gem "searchkick"                                      # Elastic Search integration
gem 'delayed_job_active_record'                       # asynchronous Jobs
gem "daemons"                                         # to daemonize delayed_job
gem "delayed_job_web"                                 # Web interface for delayed job

gem "holidays"                                        # Determine if there is a public holiday
gem "naught"                                          # Null Object library

gem "i18n-js", :git => "https://github.com/fnando/i18n-js"  # Javascript Internationalization
gem 'ahoy_matey'                                      # User tracking
gem 'activeuuid', '>= 0.5.0'
gem "memoist"                                         # Memoizing methods

group :staging do
#  gem "mercator_mesonic", path:"vendor/engines/mercator_mesonic" # Engine for integrating Mesonic ERP System
#  gem "mercator_legacy_importer", path:"vendor/engines/mercator_legacy_importer"# Engine for importing Legacy Data
end

gem 'try_to'                                          # checks for methods existance and avoids dumps
gem 'friendly_id', '~> 5.0.0'                         # Friendlier URLs for webpages
gem 'codemirror-rails', '~> 5.2.0'                    # Code Editor
gem 'exception_notification'                          # exception_notification via e-mail
gem 'awesome_print'                                   # nice, colored object representations

gem 'faker'                                           # creating (faking) demo data
gem "RedCloth"                                        # Textile rendering
gem "redcarpet"                                       # Markdown rendering
gem "truncate_html"                                   # Truncates HTML closing tags
gem 'gravtastic'                                      # Gravatar images
gem 'podlove-web-player-rails'                        # HTML5 Audio Player
gem "twitter"                                         # Twitter Posts
gem 'htmlentities'                                    # decoding HTML entities
gem "rails_autolink"                                  # auto_link helper removed from Rails 3.1
gem 'rubyzip', "1.1.7"                                # Exchange for broken internal zip library